# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('price', models.CharField(max_length=10)),
                ('open_price', models.CharField(max_length=10)),
                ('pre_close_price', models.CharField(max_length=10)),
                ('high_price', models.CharField(max_length=10)),
                ('low_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.User'),
        ),
    ]
